### ISSUE TITLE
Remove all usages of openssl_free_key()

### ISSUE THREAD

**Issue by budiony** [eXtreme-bg/borica-emv-3ds#10]
Remove all usages of `openssl_free_key()` as it is now **deprecated**, and the code produces warnings/errors in the future. More info at https://www.php.net/manual/en/function.openssl-free-key.php

**Comment by eXtreme-bg** [comment]
Thanks for reporting @budiony.
It's already fixed in 0575d9c191eb91cfe4ec5bb9800799ef9feb1f78.
