### ISSUE TITLE
Add missing response properties to the Response class

### ISSUE THREAD

**Issue by budiony** [eXtreme-bg/borica-emv-3ds#13]
There a few useful (and important by my opinion) properties, which are not added inside `Response` class, those are according the  new documentation v.3.0 of APGW and those properties are used to verify by external entity (i.e. accountant) that the card belongs to given user. See below, all the properties are **conditional**:

`AUTH_STEP_RES`=> Status of the authentication, used in scheme 3-D Secure
`CARDHOLDERINFO`=> Information regarding the cardholder, provided by ACS issuer. Note: the e-commerce system **must** visualize this field to customer
`CARD_BRAND`=> The brand of the card (i.e. Visa, MasterCard, etc.)

**Comment by eXtreme-bg** [comment]
Hi @budiony, thanks a lot for the issue. I received the new version of the API specification yesterday and will update the library by the end of this week.

**Comment by eXtreme-bg** [comment]
@budiony The end of the week has finally come :) I just implemented it in the latest version v1.0.
