### ISSUE TITLE
MAC_GENERAL support

### ISSUE THREAD

**Issue by borisdelev** [eXtreme-bg/borica-emv-3ds#14]
From last Borica documentation MAC fields (Signature) are changed and this library will not work after 21 july 2023 until MAC_GENERAL is provided.

**Comment by eXtreme-bg** [comment]
Hi @borisdelev, thanks a lot for the information. I received the new version of the API specification today and will update the library before the dead line.

**Comment by borisdelev** [comment]
Great you are!

**Comment by eXtreme-bg** [comment]
@borisdelev It's already implemented in the latest version v1.0. Make sure to read the updated README file. If you have questions or problems during implementation, throw me a PM.

**Comment by borisdelev** [comment]
Tomorrow will upgrade 😊 thanks for what uve done.

... And may the force be with you! Aways.
