### ISSUE TITLE
HTML attribute of form's submit button is misspelled

### ISSUE THREAD

**Issue by budiony** [eXtreme-bg/borica-emv-3ds#2]
In `Request.php` file, the method `renderForm()` has a form with one "submit" button with misspelled attribute, it should be ` type="submit" ` instead of ` type="submut"`.

**Comment by eXtreme-bg** [comment]
Thanks for reporting @budiony.
It's already fixed in [0c73e481e033b7b1dfe79ad4a66f56c8adf8560](https://github.com/eXtreme-bg/borica-emv-3ds/commit/f0c73e481e033b7b1dfe79ad4a66f56c8adf8560).
