### ISSUE TITLE
Return type of method withPost() should be changed as it can return null values

### ISSUE THREAD

**Issue by budiony** [eXtreme-bg/borica-emv-3ds#5]
The method `withPost()` inside class `Response` should be changed as follows as **it can return** null values (PHP 7.1+):
```
public static function withPost(array $postData) : ?Response {
// The rest of code
}
```
This change is mandatory since post data, returned from Borica can be corrupted and produces fatal error `Return value must be an instance of Response, null returned...` Also a very good programming practice is to wrap in `try-catch` such scenarios.

**Comment by eXtreme-bg** [comment]
Thanks for reporting @budiony.
It's already quick fixed in 76f8fe7a8ef60d71f503d12948c841e702b0a9e4. I'll reimplement using try-catch in the future.
