### ISSUE TITLE
Class property misspelled

### ISSUE THREAD

**Issue by budiony** [eXtreme-bg/borica-emv-3ds#7]
Inside class `Response` the property `originalTranscationType` is misspelled, also the `TRAN_TRTYPE` which is assigned to this property **is not returned with the response** anymore, so maybe this property can be deleted.

**Comment by eXtreme-bg** [comment]
Thanks for reporting @budiony.
It's already fixed in 92732793253720f998018b664725e95fe18842df. The property is part of the `Response` because I plan to reuse the class for all the transactions.
